### ISSUE TITLE
CachableLookup preventing Jest from exiting

### ISSUE THREAD

**Issue by drewish** [sendamply/amply-js#2]
I'm not sure if this or CachableLookup is the right place to report it, but it appears a dependency of this module is preventing Jest from shutting down after running tests. When run with the `--detectOpenHandles` option I'm seeing:
```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  DNSCHANNEL

      at new CacheableLookup (../node_modules/cacheable-lookup/source/index.js:91:14)
      at new Request (../node_modules/amply.js/lib/request.js:64:21)
      at new Client (../node_modules/amply.js/lib/client.js:9:20)
      at Object.<anonymous> (../node_modules/amply.js/index.js:4:18)
```
I'd opened https://github.com/szmarczak/cacheable-lookup/issues/58 to see if they could help but the error goes away when I comment out these two lines:

https://github.com/sendamply/amply-js/blob/3d726e373b4a72e4477c175087d8d7ef521ed070/lib/request.js#L64-L65

I'll try downgrading to the 0.0.2-rc.8 release and see if that addresses it.

**Comment by drewish** [comment]
Maybe the solution is to just upgrade Jest? https://github.com/facebook/jest/pull/11470 Seems like they no longer think this is a problem.
